config/routes.rb
GLMP::Application.routes.draw do
  resources :posts do
    get 'page/:page', :action => :index, :on => :collection
  end
  resource :login, :only => [:create, :destroy], :controller => 'sessions'
  resource :users, :only => [:new, :create, :edit, :update]
  match "/home" => "posts#index"
  root :to => "sessions#new"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  paginates_per 3
  delegate :email, :name, :title, to: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic

  has_secure_password
  has_gravatar
  has_many :posts
  attr_accessor :password_confirmation

  validates_presence_of :password_digest
  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email

  def can_edit_post?( post )
    self.is_admin? || self.id == post.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  before_filter :require_login

  def current_user
    if session[:user_id]
      @current_user ||= User.find session[:user_id]
    else
      @current_user
    end
  end

  def require_login
    unless current_user
      redirect_to root_url, notice: "Login required."
    end
  end
end

app/controllers/posts_controller.rb
require 'kramdown'
require 'rinku'

class PostsController < ApplicationController
  helper_method :post

  def index
    @posts = Post.order(:created_at).page params[:page]
  end

  def create
    if post.save
      redirect_to posts_url(page: Post.page.num_pages)
    else
      index
    end
  end

  def update
    if post.update_attributes params[:post]
      redirect_to posts_url(page: params[:page])
    else
      index
    end
  end

  private

  def post
    @post = if params[:id]
      Post.find params[:id]
    else
      current_user.posts.new params[:post]
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  layout 'login'

  def new
    redirect_to home_url if session[:user_id]
  end

  def create
    if user = User.find_by_name( params[:name] ).try( :authenticate, params[:password] )
      session[:user_id] = user.id
      redirect_to home_url
    else
      flash.now[:error] ="Username/password combination not recognized."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]
  layout 'login'
  helper_method :user

  def new
    session[:user_id] = nil
  end

  def create
    if sanitize( params[:ramen] ) == 'ramen' && user.save
      session[:user_id] = user.id
      redirect_to home_url
    else
      render :new
    end
  end

  def update
    if user.update_attributes params[:user]
      redirect_to home_url
    else
      render :edit
    end
  end

  private

  def user
    @user ||= if current_user
      current_user
    else
      User.new params[:user]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GLMP</title>
    <%= stylesheet_link_tag     "application" %>
    <%= javascript_include_tag  "https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" %>
    <%= javascript_include_tag  "application" %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <section id="forum_page">
    <%= yield %>
  </section>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Make a Post</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <h1 id="login">GLMP</h1>
  <%= yield %>
</body>
</html>

app/views/posts/_edit.html.erb
<%= form_for post do |f| %>
  <%= f.text_area(:content, :rows => 10) %>
  <div class="form_action">
    <%= f.submit post.new_record? ? "Post Reply" : "Edit Post", class: "add-reply" %>
  </div>
  <%= hidden_field_tag :page, params[:page] %>
<% end %>

app/views/posts/_new.html.erb
<%= form_for post do |f| %>
  <%= f.text_area(:content, :rows => 10) %>
  <div class="form_action">
    <%= f.submit "Post Reply", class: "add-reply" %>
  </div>
  <%= hidden_field_tag :page, params[:page] %>
<% end %>

app/views/posts/_post.html.erb
<article id="<%= post.id %>" style="background-image: url('<%= post.user.gravatar_url( secure: true, default: 'retro', size: 50 ) %>');">
  <div class="post-meta">
    <%= link_to post.id, posts_path( page: params[:page], anchor: post ) %>
  </div>

  <hgroup class="post-title">
    <h1><%= post.name %></h1>
    <h2><%= post.title %></h2>
  </hgroup>

  <section class="post-content">
    <%= sanitize Kramdown::Document.new( Rinku.auto_link( post.content ) ).to_html %>
  </section>

  <div class="post-pop">
    <% if current_user.can_edit_post?( post ) %>
      <%= link_to 'Edit', edit_post_path( post ), class: "post-edit" %>
    <% end %>
  </div>
</article>

app/views/posts/edit.html.erb
<div class="edit_post">
  <h1>Edit Post</h1>
  <%= render partial: "edit" %>
</div>

app/views/posts/index.html.erb
<header>
  <%= link_to "Settings", edit_users_url, id: "settings" %>
  <%= link_to "Sign out", login_url, method: :delete, id: "logout" %>
  <hgroup>
    <h1><%= link_to "Make a Post", posts_path %></h1>
    <h2>( <%= link_to "Newest Post", posts_path( page: @posts.num_pages, anchor: @posts.last )%> )</h2>
  </hgroup>
</header>
<hr />

<%= link_to "Add Reply", "whateverthenewpostrouteis", class: "add-reply" %>
<%= paginate @posts %>

<section id="posts">
  <%= render @posts %>
</section>

<%= link_to "Add Reply", "whateverthenewpostrouteis", class: "add-reply" %>
<%= paginate @posts %>
<hr />

<div id="quick-reply">
  <h1>Quick Reply</h1>
  <%= render partial: "edit" %>
</div>

app/views/posts/new.html.erb
<div class="new_post">
  <h1>Add Reply</h1>
  <%= render partial: "edit" %>
</div>

app/views/users/edit.html.erb
<%= form_for user, url: users_path, html: { class: "user_form", multipart: true } do |f| %>
  <div class="form_field" %>
    <%= f.label :title, 'Title:' %>
    <%= f.text_field :title %>
  </div>
  <div class="form_field" %>
    <%= f.label :email, 'Email:' %>
    <%= f.file_field :email, placeholder: "for gravatar" %>
  </div>
  <div class="form_action" %>
    <%= f.submit "Save preferences", class: "button" %>
  </div>
<% end %>
<%= link_to 'home', home_url, class: "nav_link" %>

app/views/users/new.html.erb
<h2>Create account</h2>
<hr />

<section id="new_user_section">
  <% user.errors.full_messages.each do |error| %>
    <p class="error"><%= error %></p>
  <% end %>

  <%= form_for user, html: { class: "user_form", multipart: true } do |f| %>
    <div class="form_field">
      <%= f.label :name, 'Username:' %>
      <%= f.text_field :name %>
    </div>
    <div class="form_field">
      <%= f.label :email, 'Email:' %>
      <%= f.text_field :email, placeholder: "for gravatar" %>
    </div>
    <div class="form_field">
      <%= f.label :title, 'Title:' %>
      <%= f.text_field :title %>
    </div>
    <div class="form_field">
      <%= f.label :password, 'Password:' %>
      <%= f.password_field :password %>
    </div>
    <div class="form_field">
      <%= f.label :password_confirmation, 'Repeat password:' %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="form_field">
      <%= label_tag :ramen, "Best food ever:" %>
      <%= text_field_tag :ramen %>
    </div>
    <div class="form_action">
      <%= f.submit 'Register', class: "button" %>
    </div>
  <% end %>
  </section>
<%= link_to 'home', home_url, class: "nav_link" %>